### BUILDING FIRST WEBSITE WITH FLASK WEBSITE FRAMEWORK
# PURPOSE: BUILD SIMPLE 7-CODE LINE WEBPAGE W/ PYTHON FOR INTRODUCTION INTO FLASK
# VERSION: 1.0
# DEPENDENCIES: 'PIP INSTALL FLASK' IN CMD TO INSTALL NECESSARY FLASK LIBRARY

# STEP 1 - IMPORT INSTALLED FLASK CLASS FROM THE INSTALLED LIBRARY
from flask import Flask                  # IMPORTING THE FLASK CLASS FROM THE FLASK INSTALLED LIBRARY

# STEP 2 - CREATE A VARIABLE CONTAINING OUR FLASK OBJECT, WHICH PASSES THE 'NAME' PARAMETER
app = Flask(__name__)                  # VARIABLE NAME 'NAME' INSTANTIATES OUR APP FLASK OBJECT

# STEP 3 - DEFINE THE APP.ROUTE THAT ULTIMATELY WILL END UP BEING OUR HOME PAGE
@app.route('/')                        # FURTHER ON THIS WILL END UP BEING THE URL STRING WE WANT

# STEP 4 - DEFINING A FUNCTION THAT (AT THIS STAGE IN THE PROCESS) ONLY RETURNS A PRINTED MESSAGE WHEN CALLED
def home():
    return "Website Content goes here!"

# STEP 5 - DEFINING CONDITIONAL THAT TRIGGERS OUR WEB APP TO RUN WHEN TRUE
if __name__ == "__main__":              # WE WANT OUR WEB APP TO RUN, IF THE __NAME__ VARIABLE CONTAINS THE __MAIN__ ARGUMENT (FOR NOW)
    app.run(debug=True)                 # CALLING THE .RUN() METHOD ON OUR FLASK OBJECT, WHICH ALLOWS US TO OPEN THE WEBPAGE FROM PORT 5000